### ISSUE TITLE
Syntax examples needed for adding typed literals

### ISSUE THREAD

**Issue by NovasTaylor** [cran/redland#2]
Please consider adding examples for creating typed literals. In the documentation I do not see how to do this. For example, adding a label as a string type. 

In the rrdf package my syntax is:

add.data.triple(cdiscpilot01,
  paste0(MYPREFIX, "sdtm-graph"), 
  paste0(DCTERMS, "title"),
  paste0("A descriptive title for my graph."), **type="string"**
)
From my reading of the docs it appears I need to use the librdf_model_add_typed_literal_statement , but I cannot find examples of adding xsd:string, integer, datetime, etc..

librdf_model_add_typed_literal_statement ( cdiscpilot01,
  new("Statement", world=world, 
    paste0(MYPREFX, "sdtm-graph"),
    paste0(RDFS, "label"),
    paste0("A descriptive title for my graph."),
    **??language??,**
    **??type??"**
    )
)
I am happy to contribute examples to the repository here if you can assist me overcoming this hurdle.

Cheers,

Tim

**Comment by gaborcsardi** [comment]
Hi, this is a read-only mirror of CRAN, please contact the original package authors. See the DESCRIPTION file. Thanks.

**Comment by NovasTaylor** [comment]
Apologies for this oversight. I will contact the authors.   Thank you.

**Comment by NovasTaylor** [comment]
Moved to developer's github. http://librdf.org/bindings/
